# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CD_cpp <- function(h0, es, se, w, h = 1e-4) {
    .Call(`_edgemeta_CD_cpp`, h0, es, se, w, h)
}

crpsCPP <- function(s, t) {
    .Call(`_edgemeta_crpsCPP`, s, t)
}

pfctedgew <- function(h0, es, se, w) {
    .Call(`_edgemeta_pfctedgew`, h0, es, se, w)
}

Q_cpp <- function(es, se, tau2) {
    .Call(`_edgemeta_Q_cpp`, es, se, tau2)
}

dQIVWE <- function(es, se, tau2) {
    .Call(`_edgemeta_dQIVWE`, es, se, tau2)
}

ftau2 <- function(es, se, tau2) {
    .Call(`_edgemeta_ftau2`, es, se, tau2)
}

nor_ctau2 <- function(es, se, utau2) {
    .Call(`_edgemeta_nor_ctau2`, es, se, utau2)
}

jointCD <- function(mu, tau2, es, se, w, C) {
    .Call(`_edgemeta_jointCD`, mu, tau2, es, se, w, C)
}

marCDsingle <- function(mu, es, se, w, utau2) {
    .Call(`_edgemeta_marCDsingle`, mu, es, se, w, utau2)
}

marCD <- function(mu, es, se, w, utau2) {
    .Call(`_edgemeta_marCD`, mu, es, se, w, utau2)
}

reff <- function(es, se, w, utau2, grid_step = 1e-2) {
    .Call(`_edgemeta_reff`, es, se, w, utau2, grid_step)
}

samplemu <- function(s_tau2, es, se, w) {
    .Call(`_edgemeta_samplemu`, s_tau2, es, se, w)
}

samponemu <- function(s_tau2, es, se, w) {
    .Call(`_edgemeta_samponemu`, s_tau2, es, se, w)
}

samptau2 <- function(B, es, se, upper) {
    .Call(`_edgemeta_samptau2`, B, es, se, upper)
}

samponetau2 <- function(es, se, upper) {
    .Call(`_edgemeta_samponetau2`, es, se, upper)
}

samplemusimple <- function(B, tau2, es, se, w) {
    .Call(`_edgemeta_samplemusimple`, B, tau2, es, se, w)
}

