# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Q_cpp <- function(es, se, tau2, mu_hat) {
    .Call(`_metaprediction_Q_cpp`, es, se, tau2, mu_hat)
}

dQ_cpp <- function(es, se, tau2, mu_hat) {
    .Call(`_metaprediction_dQ_cpp`, es, se, tau2, mu_hat)
}

ftau2_cpp <- function(es, se, tau2, mu_hat) {
    .Call(`_metaprediction_ftau2_cpp`, es, se, tau2, mu_hat)
}

sample_one_tau2 <- function(es, se, mu_hat, upper) {
    .Call(`_metaprediction_sample_one_tau2`, es, se, mu_hat, upper)
}

sample_tau2_cpp <- function(ns, es, se, mu_hat, upper) {
    .Call(`_metaprediction_sample_tau2_cpp`, ns, es, se, mu_hat, upper)
}

pfct_edge_cpp <- function(h0, es, se) {
    .Call(`_metaprediction_pfct_edge_cpp`, h0, es, se)
}

sample_one_mu <- function(s_tau2, es, se) {
    .Call(`_metaprediction_sample_one_mu`, s_tau2, es, se)
}

sample_mu_cpp <- function(s_tau2, es, se) {
    .Call(`_metaprediction_sample_mu_cpp`, s_tau2, es, se)
}

cd_single <- function(h0, es, se, h) {
    .Call(`_metaprediction_cd_single`, h0, es, se, h)
}

CD_cpp <- function(h0, es, se, h = 1e-4) {
    .Call(`_metaprediction_CD_cpp`, h0, es, se, h)
}

