# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cd_single <- function(h0, es, se, h = 1e-4) {
    .Call(`_metaprediction_cd_single`, h0, es, se, h)
}

CD_cpp <- function(h0, es, se, h = 1e-4) {
    .Call(`_metaprediction_CD_cpp`, h0, es, se, h)
}

p_wald <- function(x, es, se) {
    .Call(`_metaprediction_p_wald`, x, es, se)
}

pfctedge <- function(h0, es, se) {
    .Call(`_metaprediction_pfctedge`, h0, es, se)
}

opti_edge <- function(es, se) {
    .Call(`_metaprediction_opti_edge`, es, se)
}

opti_num <- function(es, se, point = TRUE, ci = TRUE, levelci = 0.95) {
    .Call(`_metaprediction_opti_num`, es, se, point, ci, levelci)
}

Q_cpp <- function(es, se, tau2) {
    .Call(`_metaprediction_Q_cpp`, es, se, tau2)
}

dQ_cpp <- function(es, se, tau2, h = 1e-4) {
    .Call(`_metaprediction_dQ_cpp`, es, se, tau2, h)
}

dQIVWE <- function(es, se, tau2) {
    .Call(`_metaprediction_dQIVWE`, es, se, tau2)
}

ftau2 <- function(es, se, tau2) {
    .Call(`_metaprediction_ftau2`, es, se, tau2)
}

samponemu <- function(s_tau2, es, se) {
    .Call(`_metaprediction_samponemu`, s_tau2, es, se)
}

samplemu <- function(s_tau2, es, se) {
    .Call(`_metaprediction_samplemu`, s_tau2, es, se)
}

samponetau2 <- function(es, se, upper) {
    .Call(`_metaprediction_samponetau2`, es, se, upper)
}

samptau2 <- function(ns, es, se, upper) {
    .Call(`_metaprediction_samptau2`, ns, es, se, upper)
}

samplemusimple <- function(n_samples, tau2, es, se) {
    .Call(`_metaprediction_samplemusimple`, n_samples, tau2, es, se)
}

